name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
      SERVER_IP: ${{secrets.SERVER_IP}}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Fetch Hugo themes
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: |
          hugo \
            --minify \
            --environment production \
            --baseUrl "https://blog.practicalscript.com/"
      # - name: Deploy
      #   run: |
      #     which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y  )
      #     eval $(ssh-agent -s)
      #     ssh-add <(echo "$SSH_PRIVATE_KEY" )
      #     mkdir -p ~/.ssh
      #     chmod 700 ~/.ssh
      #     ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
      #     chmod 644 ~/.ssh/known_hosts
      #     scp -r ./public/* root@$SERVER_IP:/var/www/html
